build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank account related Prod APIs "
  contactDetails:
    name: "Natrix - Developer"
    email: "natrix@eazybank.com"
  onCallSupport:
    - (959) 427778544
    - (959) 427778555