services:
  configserver:
    image: hanlynnaung7/configserver:v1
    container_name: configserver-ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  accounts:
    image: hanlynnaung7/account:v1
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: account
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default

  card:
    image: hanlynnaung7/card:v1
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: card
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default

  loan:
    image: hanlynnaung7/loan:v1
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: loan
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default

networks:
  eazybank:
    driver: bridge