version: "3.9"

# Reusable base configurations using anchors
x-network-deploy-service: &network-deploy-service
  networks:
    - eazybank

x-microservice-db-config: &microservice-db-config
  <<: *network-deploy-service
  image: mysql:8.0
  environment:
    MYSQL_ROOT_PASSWORD: root
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 5s

x-microservice-base-config: &microservice-base-config
  <<: *network-deploy-service
  deploy:
    resources:
      limits:
        memory: 700m

services:
  accountsdb:
    <<: *microservice-db-config
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsdb

  cardsdb:
    <<: *microservice-db-config
    container_name: cardsdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: cardsdb

  loansdb:
    <<: *microservice-db-config
    container_name: loansdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: loansdb
  rabbit:
    image: rabbitmq:3.12-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    <<: *microservice-base-config

  configserver:
    image: hanlynnaung7/configserver:v1
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent http://localhost:8071/actuator/health/readiness | grep "status":"UP" || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    <<: *microservice-base-config

  accounts:
    image: hanlynnaung7/account:v1
    container_name: account-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: account
    <<: *microservice-base-config

  card:
    image: hanlynnaung7/card:v1
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: card
    <<: *microservice-base-config

  loan:
    image: hanlynnaung7/loan:v1
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loan
    <<: *microservice-base-config

networks:
  eazybank:
    driver: bridge
